version: "3.5"

services:
  vaued-api:
    image: shadinikalansooriya98/vauedtest:latest
    restart: unless-stopped
    container_name: vaued-api
    # image: vaued-flask-api
    ports:
      - "5000:5000"
    networks:
      vaued-network:
        ipv4_address: 10.10.10.10

  vaued-prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    container_name: vaued-prometheus
    ports:
      - 9090:9090
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      vaued-network:
        ipv4_address: 10.10.10.11

  vaued-grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    user: "472"
    container_name: vaued-grafana
    depends_on:
      - vaued-prometheus
    ports:
      - 3000:3000
    volumes:
      - ./observability/datasource.yml:/etc/grafana/provisioning/datasource.yml
    env_file:
      - ./observability/config.observability
    networks:
      example-network:
        ipv4_address: 10.10.10.12


networks:
  vaued-network:
    name: vaued-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24